site_name: Armazenaí
theme:
  palette:

    # Light mode
    - scheme: default
      primary: yellow
      accent: yellow
      toggle:
        icon: material/theme-light-dark
        name: Mudar para o tema escuro

    # Dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/theme-light-dark
        name: Mudar para o tema claro

  language: pt
  name: material
  features:
    - navigation.tabs.sticky
    - navigation.expand

copyright: Copyright &copy; 2023 - 2023 Armazenaí

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdsreq-fga-unb/2023.1-Armazenai
  generator: false
  
repo_url: https://github.com/mdsreq-fga-unb/2023.1-Armazenai
nav :
  - 'index.md'
  - Visão geral do produto e projeto:
    - Visão geral do produto: 'Unidade 1/visaoGeralDoProduto.md'
    - Visão geral do projeto: 'Unidade 1/visaoGeralDoProjeto.md'
    - Processo de desenvolvimento de software: 'Unidade 1/processoDeDesenvolvimento.md'
    - Material do seminário de Processo de desenvolvimento de software: 'Unidade 1/materialSeminario.md'
    - Lições aprendidas: 'Unidade 1/licoes.md'
  - Unidade 2: 'Unidade 2/requisitos.md'