site_name: Armazenaí
theme:
  palette:

    # Light mode
    - scheme: default
      primary: yellow
      accent: yellow
      toggle:
        icon: material/theme-light-dark
        name: Mudar para o tema escuro

    # Dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/theme-light-dark
        name: Mudar para o tema claro

  language: pt
  name: material
  features:
    - navigation.tabs.sticky
    - navigation.expand

copyright: Copyright &copy; 2023 - 2023 Armazenaí

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdsreq-fga-unb/2023.1-Armazenai
  generator: false
  
repo_url: https://github.com/mdsreq-fga-unb/2023.1-Armazenai
nav :
  - 'index.md'
  - Unidade 1:
    - A unidade: 'Unidade 1/index-unidade1.md'
    - Visão geral do produto: 'Unidade 1/visaoGeralDoProduto.md'
    - Visão geral do projeto: 'Unidade 1/visaoGeralDoProjeto.md'
    - Processo de desenvolvimento de software: 'Unidade 1/processoDeDesenvolvimento.md'
    - Lições aprendidas: 'Unidade 1/licoes.md'
  - Unidade 2: 
    - A unidade: 'Unidade 2/index-unidade2.md'
    - Requisitos: 'Unidade 2/requisitos.md'
    - DoR e DoD: 'Unidade 2/dor&dod.md'
  - Sprints:
    - Registros das Sprints: 'Sprints/registro-sprints.md'
  - Sobre nós:
    - A equipe: 'Sobre/sobre-nos.md'