name: test-workflow
on: [pull_request]
defaults:
  run:
    working-directory: ./armazenai-fron_end
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test
